version: "3.9"
services:
  pg:
    image: postgres:13.4
    container_name: "postgres_loja_do_fabio"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2021!
      - TZ=GMT
    volumes:
      - "./database/postgres:/var/lib/postgresql/data"
    ports:
      - 5434:5432
    networks:
      - postgres-network      
  
networks:
  postgres-network:
    driver: bridge