version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nerdstore
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
  
  postgres:
    image: fabiostefani/nerdstore-postgresql:latest
    container_name: "nerdstore-postgresql"
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2021!
      - TZ=GMT    
    # ports:
    #   - 5434:5432    

  web-mvc:
    image: fabiostefani/nerdstore-web-mvc-ecommerce:latest
    #container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/WebApp.MVC/Dockerfile
    restart: always
    # ports:
    #   - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    volumes: 
            - dpkeys:/var/data_protection_keys/
    depends_on:
      - api-catalogo
      - api-identidade
      - api-cliente
      - api-bff-compras

  api-identidade:
    image: fabiostefani/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./services/Identidade/Identidade.API/Dockerfile
    restart: always
    # ports:
    #   - "5101:5101"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5101;http://+5102
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq    
      - postgres
  
  api-carrinho:
    image: fabiostefani/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    build:
      context: ../src
      dockerfile: ./services/Carrinho/Carrinho.API/Dockerfile
    restart: always
    # ports:
    #   - "5201:5201"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5201;http://+:5202
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq    
      - postgres
      - api-identidade
  
  api-catalogo:
    image: fabiostefani/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/Catalogo/Catalogo.API/Dockerfile
    restart: always
    # ports:
    #   - "5301:5301"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5301;http://+:5302
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - postgres
  
  api-cliente:
    image: fabiostefani/nerdstore-api-cliente:latest
    container_name: nerdstore-api-cliente
    build:
      context: ../src
      dockerfile: ./services/Cliente/Cliente.API/Dockerfile
    restart: always
    # ports:
    #   - "5401:5401"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5401;http://+:5402
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - postgres
  
  api-bff-compras:
    image: fabiostefani/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    build:
      context: ../src
      dockerfile: ./ApiGatways/BFF.Compras/Dockerfile
    restart: always
    # ports:
    #   - "5501:5501"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5501;http://+:5502
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - api-carrinho
      - api-pagamento
      - api-pedido

  api-pagamento:
    image: fabiostefani/nerdstore-api-pagamento:latest
    container_name: nerdstore-api-pagamento
    build:
      context: ../src
      dockerfile: ./services/Pagamento/Pagamento.API/Dockerfile
    restart: always
    # ports:
    #   - "5601:5601"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5601;http://+:5602
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - postgres
      - api-pedido

  api-pedido:
    image: fabiostefani/nerdstore-api-pedido:latest
    container_name: nerdstore-api-pedido
    build:
      context: ../src
      dockerfile: ./services/Pedido/Pedido.API/Dockerfile
    restart: always
    # ports:
    #   - "5701:5701"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5701;http://+:5702
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - postgres

  nerdstore-server:
    image: fabiostefani/nerdstore-server:latest
    container_name: nerdstore-server    
    build: 
        context: ./
        dockerfile: ./nginx/Dockerfile     
    ports:
        - "80:80"
        - "443:443"
    depends_on:
        - web-mvc      

volumes:
    dpkeys:   